<?php

namespace common\models;

use common\helpers\HDates;
use Yii;

/**
 * This is the model class for table "friends".
 *
 * @property integer $friend_from
 * @property integer $friend_to
 * @property integer $status
 * @property string $created_at
 *
 * @property User $friendFrom
 * @property User $friendTo
 */
class Friends extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'friends';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['friend_from', 'friend_to'], 'required'],
            [['friend_from', 'friend_to', 'status'], 'integer'],
            [['created_at'], 'safe'],
            [['friend_from'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['friend_from' => 'id']],
            [['friend_to'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['friend_to' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'friend_from' => Yii::t('app', 'Friend From'),
            'friend_to' => Yii::t('app', 'Friend To'),
            'status' => Yii::t('app', 'Status'),
            'created_at' => Yii::t('app', 'Created At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFriendFrom()
    {
        return $this->hasOne(User::className(), ['id' => 'friend_from']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFriendTo()
    {
        return $this->hasOne(User::className(), ['id' => 'friend_to']);
    }

    public function beforeSave($insert)
    {
        if( $insert ) {
            $this->created_at = HDates::long();
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
